name: Setup Environments
description: 'Setting up Git, NodeJS and authenticate.'

runs:
  using: 'composite'
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'

    - name: Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      shell: 'bash'

    - name: Install packages
      run: yarn install --frozen-lockfile
      shell: 'bash'
