name: Publish

on:
  workflow_dispatch:

  push:
    branches:
      - next


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Detect publish flag
        id: flag
        uses: ./.github/actions/detect-publish-flag

      - name: Publish packages
        run: yarn run publish --since-start "$PUBLISH_FLAG"
        env:
          PUBLISH_FLAG: ${{ steps.flag.outputs.flag }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
